version: "3"
services:
  seata-server:
    image: seataio/seata-server:1.4.0
    hostname: seata-server
    ports:
      - 8091:8091
      - 9898:9898
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=redis
      - SEATA_IP=xxxx
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
    volumes:
      - /root/seata-config:/root/seata-config