server:
  # 对外发布的端口, 多个application发布的时候需要修改为不同的地址;
  port: ${boss.tomcat-port:8080}
  servlet:
    # 线程内部及控制台显示的名称
    application-display-name: ${spring.application.name}
    # 上下文地址
    context-path: /
    # 指定session 里面cookie的地址;
    session:
      cookie:
        path: /
  max-http-header-size: 81920
  tomcat:
    accept-count: 1000
    max-threads: 1000
    connection-timeout: 60s
    accesslog:
      # 是否关闭接入日志, 这个在运行时线上的时候需要关闭;
      enabled: false
    mbeanregistry:
      enabled: true